### ISSUE TITLE
[Improvement] Hide the values of Boolean filters

### ISSUE THREAD

**Issue by Khalifa1997** [egytech-fyi/egytech-fyi#15]
**Describe the improvement**
Having our boolean filters displaying `: true` at the end doesn't look very user friendly, it looks very programmatic and this might make our user experience slightly worse as can be seen here:

![1](https://github.com/egytech-fyi/egytech-fyi/assets/26578518/3d31bacc-ee6e-4bb9-ad68-ebc4cbd090b9)

I have worked on a solution that would have us remove the last past which is the `: true` so it becomes:

![2](https://github.com/egytech-fyi/egytech-fyi/assets/26578518/a7b6cba2-65d8-414c-89be-c4a71fc1b4cc)

**Reproduction link**
[Dashboard](https://egytech.fyi/dashboard)

**Reproduction steps**

1. Go to the dashboard page
2. Select your Currrent Position and Salary
3. Click Compare
4. Click More Filters
5. Tick one of _Include Relocated Participants_ or _Include Participants Working Remotely for non-egyptian companies_ or both
6. Hit Apply Filters
7. Click More Filters again
8. Untick the ticked checkboxes
9. Hit Apply Filters
10. The ticked checkboxes should show: `Include Relocated: true` or `Include Remote Abroad: true`

**System Info**

```
Browsers: Chrome Version 125.0.6422.142
Node version: v20.0.0
Yarn: 1.22.19
```

**Comment by mahsayedsalem** [comment]
Brilliant, can you create a PR with this solution?

**Comment by Khalifa1997** [comment]
@mahsayedsalem Done. we should probably change the type of `cs_degree` to boolean instead of "Yes" or "No" btw
