### ISSUE TITLE
[UX Improvement] Enable Filters Reset Functionality from Slide-Over Panel

### ISSUE THREAD

**Issue by louiseyousre** [egytech-fyi/egytech-fyi#18]
**Description**: Currently, users can apply various filters through a slide-over panel. However, one critical usability issue has been identified: there is no way to reset individual filters directly within this slide-over panel. As it stands, users must close the panel and reset the filters from a different interface, which disrupts the workflow and adds unnecessary steps.

![The Slide Over](https://github.com/egytech-fyi/egytech-fyi/assets/79291748/e37512c5-b9ea-460d-97f1-9792a7f96af2)

**Current Issue**: Users must close the slide-over panel and navigate to a separate section to reset the filters. This process is cumbersome and can be frustrating for new users.

![The Place from Which they can reset the filters](https://github.com/egytech-fyi/egytech-fyi/assets/79291748/5ff482e3-9118-4e9e-8922-1af72e57941a)

**Comment by MrViometal** [comment]
@Khalifa1997 I believe either a reset on the filters' drawer or even to have a clear button on each filter by itself. A reset button next to the more filters button doesn't really add much value and may make the area crowded

**Comment by Khalifa1997** [comment]
> @Khalifa1997 I believe either a reset on the filters' drawer or even to have a clear button on each filter by itself. A reset button next to the more filters button doesn't really add much value and may make the area crowded

Instead of having a reset button for each input (maybe antd has a clearable prop for inputs) we could instead have one button called clear and we'd align it next to apply filters in the sidebar where it would take 25-35% of the horizontal space

**Comment by MrViometal** [comment]
@Khalifa1997 antd sadly doesn't have a clearable prop for the Select component which we use heavily at the moment, I have opened a PR https://github.com/egytech-fyi/egytech-fyi/pull/22 for the fix, I will postpone merging it today.

Kindly have a look and see if you have any comments/improvements. :)
