### ISSUE TITLE
[Feature] Adding a built-in Contribute form instead of the available google form

### ISSUE THREAD

**Issue by BassemHalim** [egytech-fyi/egytech-fyi#21]
Hi, I'm thinking of adding a built-in form to fill the survey to replace the current Google form.
I built the following as an example:
![Screenshot from 2024-06-10 14-52-18](https://github.com/egytech-fyi/egytech-fyi/assets/20746657/cc7d64ab-6bda-47ba-a6b7-54fd7065dc64)
 My idea is to add a new endpoint "/survey" to the backend API to fetch the latest survey questions and to POST the survey answers. So, A GET request returns a questionnaire and a POST submits the answer.
Also, I am not sure how the DB is currently updated but I am assuming this endpoint might already exist but is private?

So I was wondering if this is something I can work on? I can work on the frontend and backend.

**Comment by MrViometal** [comment]
Thanks @BassemHalim for the suggestion, we already have a project in draft at the moment to develop the participation form https://github.com/orgs/egytech-fyi/projects/1, feel free to open a PR with your changes and kindly write a detailed description to help us review it as I believe it is going to have a lot of changes.

Kindly tell me if you need to collaborate on that or have any questions in mind.

**Comment by BassemHalim** [comment]
I will try to tackle it on my own for now but I will probably need some help.
I have a couple of questions: 
- For the form, I was thinking of a single page form ( instead of multiple pages like google forms) what do you think? or do you prefer multiple pages?
- Can I get the form's questions in any format? (Instead of typing all of those questions)
- The backend depends on D1, which I am assuming I won't have access to, so do you have any recommendations for how to test any backend code?

**Comment by MrViometal** [comment]
@mahsayedsalem any thoughts?

**Comment by mahsayedsalem** [comment]
The pages in Google forms goes to different paths depending on answers.

For example, engineering will go to engineer specific page to ask about programming languages, frameworks, etc.

Here's the source of questions: https://t.co/QvtW6ei2Kx

**Comment by BassemHalim** [comment]
Oh ok, didn't know the form is dynamic. Just a heads up, a couple options in the form go directly to salary information like "UI/UX Designer/Engineer" and "CRM Developer" not sure if that's intentional.

Regarding the backend, do you have any tips for development and testing? since the code depends on the D1 database.

**Comment by mahsayedsalem** [comment]
If you have time and capacity to work on the frontend I can definitely work on the backend side! 🎉

**Comment by mahsayedsalem** [comment]
@MrViometal had a very good starting point that we can build on

**Comment by MrViometal** [comment]
I will share the form repo with you later today @BassemHalim

**Comment by BassemHalim** [comment]
Sounds good, I worked on the frontend today and I finished a big portion of the form. I will  work on breaking it into multiple steps/pages. 
A screenshot of the progress so far (it's very long :) )
[https://github.com/egytech-fyi/egytech-fyi/assets/20746657/2844ef51-2dd4-4886-85fb-cd26420a9e8e](https://github.com/egytech-fyi/egytech-fyi/assets/20746657/2844ef51-2dd4-4886-85fb-cd26420a9e8e)

**Comment by BassemHalim** [comment]
What do you think of the style so far?
![image](https://github.com/egytech-fyi/egytech-fyi/assets/20746657/a5238220-c8e2-46d5-a09e-2b30ee1132cc)

**Comment by MrViometal** [comment]
I like the idea of it but I don't think the horizontal alignment of the questions and answers is the best way to go accessibility wise and it can get confusing for some people

Let me share the draft report I made a while back and lets see if combining both ideas can be beneficial

**Comment by MrViometal** [comment]
@BassemHalim please check https://github.com/MrViometal/EgyptSalaries, I have sent you an invite for access

**Comment by BassemHalim** [comment]
Good point, didn't think of that. I will look at the repo and try to combine the ideas.

**Comment by MrViometal** [comment]
@BassemHalim let me know if you need any help, we can meet on my weekend (Saturday and Sunday) if you need

**Comment by BassemHalim** [comment]
ok I'm down, how can I contact you?

**Comment by MrViometal** [comment]
@BassemHalim sorry I didn't check my notifications so I couldn't reply earlier 

Through linkedin or twitter and then we can decide if we want to use any other platform 

Twitter: @_adawy_
Linkedin: in/abdelrahman-el-adawy

**Comment by BassemHalim** [comment]
@MrViometal No worries, I sent you an invite on LinkedIn

**Comment by BassemHalim** [comment]
Created [Pull request](https://github.com/egytech-fyi/egytech-fyi/pull/39)
