### ISSUE TITLE
Reports Page (Right Scroller with class named ant-anchor-wrapper)

### ISSUE THREAD

**Issue by abdallahmmu** [egytech-fyi/egytech-fyi#33]
The div have a max height without making the overflow-y: auto which made it not responsive 

good for contribution, also I can made it

![Screenshot_7](https://github.com/egytech-fyi/egytech-fyi/assets/40822362/5c6606d0-d15d-4f6f-9194-d2887714f492)

**Comment by iahmedgamal** [comment]
@abdallahmmu Nice catch, go for it 👌

**Comment by abdallahmmu** [comment]
on it thank you 👌
