### ISSUE TITLE
Add CONTRIBUTING.md file to guide new contributors

### ISSUE THREAD

**Issue by iahmedgamal** [egytech-fyi/egytech-fyi#37]
### Description
Create a CONTRIBUTING.md file with:

Setup instructions
Issue and PR guidelines
Coding standards

### Why It's Useful
Even with a contribution section in the README.md, the CONTRIBUTING.md file offers:

## Separation of Concerns:
 Keeps README.md focused on usage, while CONTRIBUTING.md details guidelines.

## Visibility: 
GitHub highlights it for contributors opening PRs or issues.

## Clarity: 
Provides detailed guidelines without cluttering README.md.

**Comment by mahsayedsalem** [comment]
Let's do that!

And we can remove the names of the initial builders from the website footer as well

**Comment by iahmedgamal** [comment]
On it
