### ISSUE TITLE
Suggestion to Add .editorconfig and CONTRIBUTE.md Files

### ISSUE THREAD

**Issue by ahmadalfy** [egytech-fyi/egytech-fyi#5]
I would like to suggest adding an `.editorconfig` file to this project to help maintain consistent coding styles across different editors and IDEs. This will be particularly useful given that you will start to have new PRs with changes related to indentation types and styles.

Benefits of Adding an `.editorconfig` File

1. Consistency: Ensures uniform coding styles (indentation, spacing, etc.) across different developers' environments.
2. Readability: Improves code readability and reduces diffs related to style changes.
3. Efficiency: Saves time by automating the enforcement of coding standards.

Here is a basic example of an `.editorconfig` file that could be adapted for this project:

```
root = true

[*]
indent_style = space
indent_size = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false
```

Suggestion to Create a CONTRIBUTE.md File

Additionally, I recommend creating a `CONTRIBUTE.md` file to outline the contribution guidelines. This file can provide valuable information such as:

1. Coding Standards: Clear guidelines on coding styles and practices.
2. Commit Messages: Instructions on writing meaningful commit messages.
3. Pull Request Process: Steps for submitting a PR, including code review and testing procedures.
4. Branching Model: Information on the branching strategy used by the project (e.g., feature branches, main branch protection).
5. Issue Reporting: Guidelines for reporting issues, including how to write descriptive and useful bug reports.

I will be happy to submit a PR to address those

**Comment by mahsayedsalem** [comment]
Please go ahead!

**Comment by MrViometal** [comment]
Please do, would love to see how it is done and learn from it ❤️

**Comment by geemeows** [comment]
Adding a PULL_REQUEST_TEMPLATE.md to the repo is important since it ensures that all PRs follow a consistent format and helps reviewers quickly understand the changes being proposed, as they know what information to expect and where to find it.
Here's an example 
```
## 📖 Description
_Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #(issue)

## Type of change
_Please delete options that are not relevant._

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## 🧪 How Has This Been Tested?
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

## 📋 Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
```

**Comment by mahsayedsalem** [comment]
@geemeows can you create a PR with that? 

Thanks a million

**Comment by geemeows** [comment]
> @geemeows can you create a PR with that?
> 
> Thanks a million

Done. HYG -> https://github.com/egytech-fyi/egytech-fyi/pull/7

**Comment by Khalifa1997** [comment]
We can also add issue templates since we're at it, it's going to be much more helpful for new developers and even experienced ones to have a template ready that they can fill just like we have currently with pull requests.

I found this link that could help! [Configuring issue templates for your repository
](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
